server {
	server_name    	= localhost;		# server name
	host		   	= 127.0.0.1;			# host to listen on
	port		   	= 8080;					# port to listen on -> expects one single number -> 80:80 == DOCKER syntax
	root		   	= www/html;         	# root directory for serving files
	index		   	= index.html;			# default page to serve
	allowed_methods	= GET;					# allowed HTTP methods
	autoindex	   	= false;	            # directory listing off b/o security reasons
	max_body_size  	= 10000000;				# 10mb - maximum allowed size of client request body
	
	# Root location serves static files (Homepage) 
	location / {
		root 	= www/html;
		index 	= index.html;
		allowed_methods = GET;
	}

}

