server {
	server_name    	= localhost;
	host		   	= 127.0.0.1;
	port		   	= 8080;
	root		   	= www/html;
	index		   	= index.html;
	allowed_methods	= GET; 	
	autoindex	   	= false;
	max_body_size  	= 10000000;
	error_page      = 400 www/errors/400.html;
	error_page      = 403 www/errors/403.html;
	error_page      = 404 www/errors/404.html;
	error_page      = 405 www/errors/405.html;
	error_page      = 413 www/errors/413.html;
	error_page      = 500 www/errors/500.html;
	error_page      = 501 www/errors/501.html;
	error_page      = 504 www/errors/504.html;
	location / {
		root 	= www/html;
		index 	= index.html;
		allowed_methods = GET POST DELETE; 
	location /uploads {
		root 			= www/uploads;
		allowed_methods = GET POST DELETE;
		uploadEnabled	= true;
		autoindex		= true;
	}
	location /cgi-bin {
		root			= www;
		is_cgi			= true;
		allowed_methods	= GET POST DELETE;
	}
	location /images {
		root 			= www/html;
		index 			= index.html;
		allowed_methods = GET;
		autoindex 		= true;				
	}
	location /redirect {
		return	= 301 http://localhost:8080/; 
	}
}
server {
	server_name    	= second_site;		
	host		   	= 0.0.0.0;			
	root			= www/second_site;
	index			= index.html;
	port		   	= 4040;				
	max_body_size 	= 10000000;			
	allowed_methods = GET POST DELETE;
	error_page      = 400 www/errors/400.html;
	error_page      = 403 www/errors/403.html;
	error_page      = 404 www/errors/404.html;
	error_page      = 405 www/errors/405.html;
	error_page      = 413 www/errors/413.html;
	error_page      = 500 www/errors/500.html;
	error_page      = 501 www/errors/501.html;
	error_page      = 504 www/errors/504.html;
	location / {
		index 			= index.html;
		autoindex 		= off;
	}
}
