# Sets defaults at the server level (root, index, error pages, etc.)
# Allows location-specific overrides (/images can allow only GET, /upload only POST and DELETE, etc.)
# Supports redirection and file uploads
# Defines server ports and hostnames for multiple servers
server {
	server_name    	= localhost;			# server name
	host		   	= 127.0.0.1;			# host to listen on
	port		   	= 8080;					# port to listen on -> expects one single number -> 80:80 == DOCKER syntax
	root		   	= www/html;          	# root directory for serving files
	index		   	= index.html;			# default page to serve
	allowed_methods	= GET;					# allowed HTTP methods
	autoindex	   	= false;	            # directory listing off b/o security reasons
	max_body_size  	= 10000000;				# 10mb - maximum allowed size of client request body
	
	# Error Pages
	error_page      = 400 www/errors/400.html;
	error_page      = 403 www/errors/403.html;
	error_page      = 404 www/errors/404.html;
	error_page      = 405 www/errors/405.html;
	error_page      = 413 www/errors/413.html;
	error_page      = 500 www/errors/500.html;
	error_page      = 501 www/errors/501.html;
	error_page      = 504 www/errors/504.html;

	# --- Location Blocks ---

	# Root location serves static files (Homepage) 
	location / {
		root 	= www/html;
		index 	= index.html;
		allowed_methods = GET; // Check if P+D are needed
	}

	# Location /upload. Handles file uploads
	location /upload {
		root 			= www/upload;
		index			= upload_index.html;
		allowed_methods = GET POST DELETE;
		uploadEnabled	= true;
		autoindex		= true;
	}

	# Location /cgi-bin. Handles CGI scripts
	location /cgi-bin {
		root			= www/cgi-bin;
		is_cgi			= true;
		allowed_methods	= GET POST; // Check if P+D are needed
	}

	# Location /images. Handles static image files
	location /images {
		root 			= www/html/images;
		index 			= images_index.html;
		allowed_methods = GET;
	}

	# Performs a permanent redirect to another URL
	location /redirect {
		return	= 301 http://www.youtube.com/; // Permanent redirect, can be a link to YT, Homepage or anything else
	}

	# Location for .bla files - POST with CGI
	location ~ \.bla$ {
		allowed_methods = POST;
		is_cgi			= true;
		cgi_executable	= cgi_test;
	}

	# Location /post_body - POST with max body size of 100
	location /post_body {
		allowed_methods = POST;
		max_body_size   = 100;
	}

	# Location /directory/ - GET with YoupiBanane as root
	location /directory/ {
		root            = YoupiBanane;
		index           = youpi.bad_extension;
		allowed_methods = GET;
	}
}

# Second server that must listen to other ports to deliver different content
server {
	server_name    	= secondsite;		# server name
	host		   	= 0.0.0.0;			# host to listen on
	root			= www/second_site;
	index			= index.html;
	port		   	= 4040;				# port to listen on
	max_body_size 	= 10000000;			# 10mb - maximum allowed size of client request body
	allowed_methods = GET POST DELETE;

	# Error Pages
	error_page      = 400 www/errors/400.html;
	error_page      = 403 www/errors/403.html;
	error_page      = 404 www/errors/404.html;
	error_page      = 405 www/errors/405.html;
	error_page      = 413 www/errors/413.html;
	error_page      = 500 www/errors/500.html;
	error_page      = 501 www/errors/501.html;
	error_page      = 504 www/errors/504.html;

	location / {
		index 			= index.html;
		autoindex 		= off;
	}
}
