# Sets defaults at the server level (root, index, error pages, etc.)
# Defines server ports and hostnames for multiple servers
server {
	server_name    	= localhost;			# server name
	host		   	= 127.0.0.1;			# host to listen on
	port		   	= 8080;					# port to listen on -> expects one single number -> 80:80 == DOCKER syntax
	root		   	= www/html;          	# root directory for serving files
	index		   	= index.html;			# default page to serve
	allowed_methods	= GET;					# allowed HTTP methods
	autoindex	   	= false;	            # directory listing off b/o security reasons
	max_body_size  	= 10000000;				# 10mb - maximum allowed size of client request body
	
	# Error Pages
	error_page      = 400 www/html/errors/400.html;
	error_page      = 403 www/html/errors/403.html;
	error_page      = 404 www/html/errors/404.html;
	error_page      = 405 www/html/errors/405.html;
	error_page      = 413 www/html/errors/413.html;
	error_page      = 500 www/html/errors/500.html;
	error_page      = 501 www/html/errors/501.html;
	error_page      = 504 www/html/errors/504.html;

	# --- Location Blocks ---

	# Root location serves static files (Homepage) 
	location / {
		root 	= www/html;
		index 	= index.html;
		allowed_methods = GET;
	}

	# Location /upload
	location /upload {
		root 			= www/upload;
		index			= upload_index.html;
		allowed_methods = GET POST DELETE;
		autoindex		= true;
	}

	# Location /cgi-bin
	location /cgi-bin {
		root			= www/cgi-bin;
		is_cgi			= true;
		cgi_executable  = /opt/pyenv/shims/python3 /usr/bin/bash /usr/bin/php-cgi;
		cgi_extension	= .py .sh .php;
		allowed_methods	= GET POST;
	}

	# Location /images
	location /images {
		root 			= www/html/images;
		index 			= images_index.html;
		allowed_methods = GET;
	}

	# Performs a permanent redirect to another URL
	location /redirect {
		return	= 301 http://www.youtube.com/;
	}
}

# Second server that must listen to other ports to deliver different content
server {
	server_name    	= secondsite;
	host		   	= 0.0.0.0;
	root			= www/second_site;
	index			= index.html;
	port		   	= 4040;
	max_body_size 	= 10000000;
	allowed_methods = GET;

	# Error Pages
	error_page      = 400 www/html/errors/400.html;
	error_page      = 403 www/html/errors/403.html;
	error_page      = 404 www/html/errors/404.html;
	error_page      = 405 www/html/errors/405.html;
	error_page      = 413 www/html/errors/413.html;
	error_page      = 500 www/html/errors/500.html;
	error_page      = 501 www/html/errors/501.html;
	error_page      = 504 www/html/errors/504.html;

	location / {
		index 			= index.html;
		autoindex 		= off;
	}
}

