	# Sets defaults at the server level (root, index, error pages, etc.)
	# Allows location-specific overrides (/images can allow only GET, /uploads only POST and DELETE, etc.)
	# Supports redirection and file uploads
	# Defines server ports and hostnames for multiple servers

	server {
		server_name    	= localhost;			# server name
		host		   	= 127.0.0.1;			# host to listen on
		port		   	= 8080;					# port to listen on
		root		   	= www/html;           	# root directory for serving files
		index		   	= index.html;			# default page to serve
		allowed_methods	= GET POST DELETE; 		# allowed HTTP methods
		autoindex	   	= off;	            	# directory listing off b/o security reasons
		max_body_size  	= 10000000;				# 10mb - maximum allowed size of client request body
		
		# Error Pages
		error_page      = 400 www/errors/400.html;
		error_page      = 403 www/errors/403.html;
		error_page      = 404 www/errors/404.html;
		error_page      = 405 www/errors/405.html;
		error_page      = 413 www/errors/413.html;
		error_page      = 500 www/errors/500.html;
		error_page      = 501 www/errors/501.html;
		error_page      = 504 www/errors/504.html;

		# Location Blocks

		# Root location serves static files (Homepage) 
		location / {
			root 	= www/html;
			index 	= index.html;
		}

		# Location /upload. Handles file uploads
		location /uploads {
			root 			= www/uploads;
			allowed_methods = POST DELETE;
			uploadEnabled	= true;
		}

		# Location /cgi-bin. Handles CGI scripts
		location /cgi-bin {
			root	= www;
			is_cgi	= true;
		}

		# Location /images. Handles static image files
		location /images {
			root 			= www/html;
			index 			= index.html;
			allowed_methods = GET;
			autoindex 		= on;				# enable directory listing for images
		}

		# Performs a permanent redirect to another URL
		location /redirect {
			return	= 301 http://localhost:8080/; // Permanent redirect, can be a link to YT, Homepage or anything else
		}
	}


	# Second server that must listen to other ports to deliver different content
	server {
		server_name    	= second_site;		# server name
		host		   	= 0.0.0.0;			# host to listen on
		port		   	= 4040;				# port to listen on
		max_body_size 	= 10000000;			# 10mb - maximum allowed size of client request body
		allowed_methods = GET POST DELETE;

		# Error Pages
		error_page      = 400 www/errors/400.html;
		error_page      = 403 www/errors/403.html;
		error_page      = 404 www/errors/404.html;
		error_page      = 405 www/errors/405.html;
		error_page      = 413 www/errors/413.html;
		error_page      = 500 www/errors/500.html;
		error_page      = 501 www/errors/501.html;
		error_page      = 504 www/errors/504.html;

		location / {
			root 			= www/second_site;
			index 			= index.html;
			autoindex 		= off;
		}
	}
